--
-- Table structure for table `caixas_pendentes`
--
TABLE `caixas_pendentes` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `valor` decimal(8,2) unsigned NOT NULL,
  `codigo_transacao` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `expiracao` int unsigned DEFAULT '604800',
  `pix_tx_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pix_payload` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pix_tentativas` int unsigned NOT NULL DEFAULT '1',
  `pix_br_code` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `pix_info_pagador` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pix_e2ed_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pix_rtr_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `data_criacao_cobranca` datetime DEFAULT NULL,
  `data_expiracao_cobranca` datetime DEFAULT NULL,
  `fechado` tinyint(1) NOT NULL DEFAULT '0',
  `data_fechamento` datetime DEFAULT NULL,
  `finalizado` tinyint(1) NOT NULL DEFAULT '0',
  `data_finalizacao` datetime DEFAULT NULL,
  `cancelado` tinyint(1) NOT NULL DEFAULT '0',
  `data_cancelamento` datetime DEFAULT NULL,
  `caixa_tipo_id` int unsigned NOT NULL,
  `caixa_status_id` int unsigned DEFAULT NULL,
  `caixa_fechamento_id` int unsigned DEFAULT NULL,
  `os_id` int unsigned NOT NULL,
  `empresa_id` int unsigned DEFAULT NULL,
  `remessa_os_id` int unsigned DEFAULT NULL,
  `tipo_remessa_id` int unsigned DEFAULT NULL,
  `usuario_pagamento_id` int unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `caixas_pendentes_caixa_tipo_id_foreign` (`caixa_tipo_id`),
  KEY `caixas_pendentes_os_id_foreign` (`os_id`),
  KEY `caixas_pendentes_empresa_id_foreign` (`empresa_id`),
  KEY `caixas_pendentes_remessa_os_id_foreign` (`remessa_os_id`),
  KEY `cptri` (`tipo_remessa_id`),
  KEY `caixas_pendentes_caixa_status_id_foreign` (`caixa_status_id`),
  KEY `caixas_pendentes_usuario_pagamento_id_foreign` (`usuario_pagamento_id`),
  KEY `caixas_pendentes_caixa_fechamento_id_foreign` (`caixa_fechamento_id`),
  CONSTRAINT `caixas_pendentes_caixa_fechamento_id_foreign` FOREIGN KEY (`caixa_fechamento_id`) REFERENCES `caixa_fechamentos` (`id`),
  CONSTRAINT `caixas_pendentes_caixa_status_id_foreign` FOREIGN KEY (`caixa_status_id`) REFERENCES `caixa_status` (`id`),
  CONSTRAINT `caixas_pendentes_caixa_tipo_id_foreign` FOREIGN KEY (`caixa_tipo_id`) REFERENCES `caixa_tipos` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `caixas_pendentes_empresa_id_foreign` FOREIGN KEY (`empresa_id`) REFERENCES `empresas` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `caixas_pendentes_os_id_foreign` FOREIGN KEY (`os_id`) REFERENCES `os` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `caixas_pendentes_remessa_os_id_foreign` FOREIGN KEY (`remessa_os_id`) REFERENCES `remessa_os` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `caixas_pendentes_usuario_pagamento_id_foreign` FOREIGN KEY (`usuario_pagamento_id`) REFERENCES `usuarios` (`id`),
  CONSTRAINT `cptri` FOREIGN KEY (`tipo_remessa_id`) REFERENCES `tipo_remessas` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=33512 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;