--
-- Table structure for table `caixas`
--
TABLE `caixas` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `valor` decimal(8,2) NOT NULL DEFAULT '0.00',
  `data_vencimento` date NOT NULL,
  `data_pagamento` datetime NOT NULL,
  `cancelado` tinyint(1) NOT NULL DEFAULT '0',
  `data_cancelamento` datetime DEFAULT NULL,
  `fechado` tinyint(1) NOT NULL DEFAULT '0',
  `data_fechamento` datetime DEFAULT NULL,
  `classificado` tinyint(1) NOT NULL DEFAULT '0',
  `data_classificacao` datetime DEFAULT NULL,
  `finalizado` tinyint(1) NOT NULL DEFAULT '0',
  `verificado` tinyint(1) NOT NULL DEFAULT '0',
  `data_verificacao` datetime DEFAULT NULL,
  `data_finalizacao` datetime DEFAULT NULL,
  `parcela` int unsigned NOT NULL DEFAULT '1',
  `quant_parcelas` int unsigned NOT NULL DEFAULT '1',
  `nome_depositante` varchar(40) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `codigo_transacao` varchar(30) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `nome_titular` varchar(40) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `doc_titular` varchar(14) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `telefone_titular` varchar(15) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `tid_cielo` varchar(36) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `bandeira_cartao` varchar(30) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL DEFAULT '99',
  `codigo_autorizacao` varchar(36) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `numero_autorizacao` varchar(36) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `nome_cartao` varchar(36) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `cc_conciliado` int NOT NULL DEFAULT '0',
  `pix_payload` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `pix_info_pagador` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `pix_e2ed_id` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `pix_rtr_id` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `observacao_financeiro` text CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci,
  `caixa_preto` tinyint(1) NOT NULL DEFAULT '0',
  `usuario_pagamento_id` int unsigned DEFAULT NULL,
  `usuario_verificacao_id` int unsigned DEFAULT NULL,
  `caixa_conta_id` int unsigned DEFAULT NULL,
  `caixa_tipo_id` int unsigned NOT NULL,
  `caixa_pendente_id` bigint unsigned DEFAULT NULL,
  `caixa_status_id` int unsigned NOT NULL,
  `caixa_fechamento_id` int unsigned DEFAULT NULL,
  `caixa_original_id` int unsigned DEFAULT NULL,
  `empresa_faturamento_id` int unsigned DEFAULT NULL,
  `financeiro_malote_classificacao_id` int unsigned DEFAULT NULL,
  `financeiro_caixa_destino_id` int unsigned DEFAULT NULL,
  `os_id` int unsigned NOT NULL,
  `ativo` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `pix_e2ed_id_UNIQUE` (`pix_e2ed_id`),
  KEY `caixas_usuario_pagamento_id_foreign` (`usuario_pagamento_id`),
  KEY `caixas_caixa_conta_id_foreign` (`caixa_conta_id`),
  KEY `caixas_caixa_tipo_id_foreign` (`caixa_tipo_id`),
  KEY `caixas_caixa_status_id_foreign` (`caixa_status_id`),
  KEY `caixas_os_id_foreign` (`os_id`),
  KEY `caixas_caixa_fechamento_id_foreign` (`caixa_fechamento_id`),
  KEY `caixas_financeiro_caixa_destino_id_foreign` (`financeiro_caixa_destino_id`),
  KEY `caixas_usuario_verificacao_id_foreign` (`usuario_verificacao_id`),
  KEY `caixas_financeiro_malote_classificacao_id_foreign` (`financeiro_malote_classificacao_id`),
  KEY `caixas_caixa_original_id_foreign` (`caixa_original_id`),
  KEY `caixas_empresa_faturamento_id_foreign` (`empresa_faturamento_id`),
  KEY `caixas_caixa_pendente_id_foreign` (`caixa_pendente_id`),
  KEY `caixas_tid_cielo_index` (`tid_cielo`),
  CONSTRAINT `caixas_caixa_conta_id_foreign` FOREIGN KEY (`caixa_conta_id`) REFERENCES `caixa_contas` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `caixas_caixa_fechamento_id_foreign` FOREIGN KEY (`caixa_fechamento_id`) REFERENCES `caixa_fechamentos` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `caixas_caixa_original_id_foreign` FOREIGN KEY (`caixa_original_id`) REFERENCES `caixas` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `caixas_caixa_pendente_id_foreign` FOREIGN KEY (`caixa_pendente_id`) REFERENCES `caixas_pendentes` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `caixas_caixa_status_id_foreign` FOREIGN KEY (`caixa_status_id`) REFERENCES `caixa_status` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `caixas_caixa_tipo_id_foreign` FOREIGN KEY (`caixa_tipo_id`) REFERENCES `caixa_tipos` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `caixas_empresa_faturamento_id_foreign` FOREIGN KEY (`empresa_faturamento_id`) REFERENCES `empresas` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `caixas_financeiro_caixa_destino_id_foreign` FOREIGN KEY (`financeiro_caixa_destino_id`) REFERENCES `financeiro_caixas_destino` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `caixas_financeiro_malote_classificacao_id_foreign` FOREIGN KEY (`financeiro_malote_classificacao_id`) REFERENCES `financeiro_malotes_classificacao` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `caixas_os_id_foreign` FOREIGN KEY (`os_id`) REFERENCES `os` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `caixas_usuario_pagamento_id_foreign` FOREIGN KEY (`usuario_pagamento_id`) REFERENCES `usuarios` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `caixas_usuario_verificacao_id_foreign` FOREIGN KEY (`usuario_verificacao_id`) REFERENCES `usuarios` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=352279 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;