--
-- Table structure for table `clientes`
--
TABLE `clientes` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `pf` tinyint(1) NOT NULL DEFAULT '1',
  `nome` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `cpf` varchar(14) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `sexo` int DEFAULT NULL,
  `data_nascimento` date DEFAULT NULL,
  `estado_civil` int DEFAULT NULL,
  `ie` varchar(14) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `ie_verificada` tinyint(1) NOT NULL DEFAULT '0',
  `im` varchar(14) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `retem_iss` tinyint(1) NOT NULL DEFAULT '0',
  `cep` varchar(8) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `logradouro` varchar(80) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `bairro` varchar(80) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `localidade` varchar(80) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `uf` char(2) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `numero` int DEFAULT NULL,
  `complemento` varchar(150) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `telefone1` varchar(15) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `telefone2` varchar(15) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `email` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `bloqueado_serasa` tinyint(1) NOT NULL DEFAULT '0',
  `observacao_serasa` varchar(30) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `crmbonus_customer_id` int unsigned DEFAULT NULL,
  `crmbonus_pin_code` varchar(4) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `crmbonus_validado` tinyint(1) NOT NULL DEFAULT '0',
  `crmbonus_data_cadastro` datetime DEFAULT NULL,
  `crmbonus_verificado` tinyint(1) NOT NULL DEFAULT '0',
  `ativo` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `clientes_deleted_at` (`deleted_at`)
) ENGINE=InnoDB AUTO_INCREMENT=85539 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;
