--
-- Table structure for table `concessionarias`
--
TABLE `concessionarias` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `nome` varchar(200) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `nome_carbel` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `razao_social` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `cnpj` varchar(14) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `ie` varchar(14) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `im` varchar(14) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `cep` varchar(8) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `logradouro` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `bairro` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `localidade` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `uf` char(2) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `numero` int NOT NULL,
  `complemento` varchar(30) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `retem_iss` tinyint(1) NOT NULL DEFAULT '0',
  `aceita_indicador1` tinyint(1) NOT NULL DEFAULT '0',
  `aceita_indicador2` tinyint(1) NOT NULL DEFAULT '0',
  `restringe_requisicao_kit` tinyint(1) NOT NULL DEFAULT '0',
  `edita_observacao_nf` tinyint(1) NOT NULL DEFAULT '0',
  `permite_deposito_ci` tinyint(1) NOT NULL DEFAULT '0',
  `permite_pcp` tinyint(1) NOT NULL DEFAULT '0',
  `dias_execucao` int unsigned NOT NULL DEFAULT '1',
  `produtivo_base_id` int unsigned DEFAULT NULL,
  `concessionaria_execucao_id` int unsigned DEFAULT NULL,
  `vendedor_responsavel_nf` tinyint(1) NOT NULL DEFAULT '0',
  `cancelamento_automatico` tinyint(1) NOT NULL DEFAULT '0',
  `dias_cancelamento_automatico` int NOT NULL DEFAULT '90',
  `cancelamento_automatico_proposta` tinyint(1) NOT NULL DEFAULT '0',
  `dias_cancelamento_automatico_proposta` int NOT NULL DEFAULT '0',
  `integracao_carbel` tinyint(1) NOT NULL DEFAULT '0',
  `chassis_nf_cortesia` enum('P','S','M') CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `numero_controle_nf_cortesia` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL DEFAULT '0',
  `carro_marca_id` int unsigned NOT NULL,
  `comissao_periodo_id` int unsigned DEFAULT NULL,
  `nota_tipo_id` int unsigned DEFAULT NULL,
  `supervisor_vendas_id` int unsigned DEFAULT NULL,
  `cluster_id` bigint unsigned DEFAULT NULL,
  `business_unit_id` bigint unsigned NOT NULL DEFAULT '1',
  `empresa_faturamento_id` int unsigned DEFAULT NULL,
  `email_vendedora` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `ramal_vendedora` varchar(11) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `gerente_nome` varchar(70) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `gerente_email` varchar(70) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `ativo` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `bloqueio` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `concessionarias_carro_marca_id_foreign` (`carro_marca_id`),
  KEY `concessionarias_comissao_periodo_id_foreign` (`comissao_periodo_id`),
  KEY `concessionarias_nota_tipo_id_foreign` (`nota_tipo_id`),
  KEY `concessionarias_supervisor_vendas_id_foreign` (`supervisor_vendas_id`),
  KEY `cci` (`cluster_id`),
  KEY `cbui` (`business_unit_id`),
  KEY `concessionarias_deleted_at` (`deleted_at`),
  KEY `concessionarias_produtivo_base_id_foreign` (`produtivo_base_id`),
  KEY `ccei` (`concessionaria_execucao_id`),
  KEY `concessionarias_empresa_faturamento_id_foreign` (`empresa_faturamento_id`),
  CONSTRAINT `cbui` FOREIGN KEY (`business_unit_id`) REFERENCES `business_units` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ccei` FOREIGN KEY (`concessionaria_execucao_id`) REFERENCES `concessionarias` (`id`),
  CONSTRAINT `cci` FOREIGN KEY (`cluster_id`) REFERENCES `clusters` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `concessionarias_carro_marca_id_foreign` FOREIGN KEY (`carro_marca_id`) REFERENCES `carro_marcas` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `concessionarias_comissao_periodo_id_foreign` FOREIGN KEY (`comissao_periodo_id`) REFERENCES `comissao_periodos` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `concessionarias_empresa_faturamento_id_foreign` FOREIGN KEY (`empresa_faturamento_id`) REFERENCES `empresas` (`id`),
  CONSTRAINT `concessionarias_nota_tipo_id_foreign` FOREIGN KEY (`nota_tipo_id`) REFERENCES `nota_tipos` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `concessionarias_produtivo_base_id_foreign` FOREIGN KEY (`produtivo_base_id`) REFERENCES `produtivo_bases` (`id`),
  CONSTRAINT `concessionarias_supervisor_vendas_id_foreign` FOREIGN KEY (`supervisor_vendas_id`) REFERENCES `funcionarios` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=119 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;