--
-- Table structure for table `cortesias`
--
TABLE `cortesias` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `mes_referencia` date NOT NULL,
  `valor_bruto` decimal(8,2) NOT NULL,
  `valor_liquido` decimal(8,2) NOT NULL,
  `retensao_iss` tinyint(1) NOT NULL DEFAULT '0',
  `paga` tinyint(1) NOT NULL DEFAULT '0',
  `data_pagamento` datetime DEFAULT NULL,
  `valor_pago` decimal(8,2) DEFAULT NULL,
  `fechada` tinyint(1) NOT NULL DEFAULT '0',
  `data_fechamento` datetime DEFAULT NULL,
  `finalizada` tinyint(1) NOT NULL DEFAULT '0',
  `data_finalizacao` datetime DEFAULT NULL,
  `cancelada` tinyint(1) NOT NULL DEFAULT '0',
  `data_cancelamento` datetime DEFAULT NULL,
  `solicitado_cancelamento` tinyint(1) NOT NULL DEFAULT '0',
  `motivo_cancelamento` text CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci,
  `observacao` text CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci,
  `email_enviado` tinyint(1) NOT NULL DEFAULT '0',
  `data_envio_email` datetime DEFAULT NULL,
  `pagamento_deposito` tinyint(1) NOT NULL DEFAULT '0',
  `concessionaria_id` int unsigned NOT NULL,
  `departamento_id` int unsigned DEFAULT NULL,
  `empresa_id` int unsigned DEFAULT NULL,
  `funcionario_cancelamento_id` int unsigned DEFAULT NULL,
  `ativo` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `cortesias_concessionaria_id_foreign` (`concessionaria_id`),
  KEY `cortesias_departamento_id_foreign` (`departamento_id`),
  KEY `cortesias_funcionario_cancelamento_id_foreign` (`funcionario_cancelamento_id`),
  KEY `cortesias_empresa_id_foreign` (`empresa_id`),
  CONSTRAINT `cortesias_concessionaria_id_foreign` FOREIGN KEY (`concessionaria_id`) REFERENCES `concessionarias` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `cortesias_departamento_id_foreign` FOREIGN KEY (`departamento_id`) REFERENCES `departamentos` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `cortesias_empresa_id_foreign` FOREIGN KEY (`empresa_id`) REFERENCES `empresas` (`id`),
  CONSTRAINT `cortesias_funcionario_cancelamento_id_foreign` FOREIGN KEY (`funcionario_cancelamento_id`) REFERENCES `funcionarios` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4854 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;