--
-- Table structure for table `estoque_entrada_produtos`
--
TABLE `estoque_entrada_produtos` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `valor_unitario` decimal(10,4) NOT NULL,
  `valor_unitario_real` decimal(10,4) unsigned NOT NULL DEFAULT '0.0000',
  `valor_icms` decimal(10,4) NOT NULL,
  `valor_icms_subst` decimal(8,2) NOT NULL DEFAULT '0.00',
  `base_icms` decimal(8,2) NOT NULL DEFAULT '0.00',
  `valor_ipi` decimal(10,4) DEFAULT NULL,
  `aliquota_ipi` decimal(4,2) DEFAULT NULL,
  `codigo` varchar(12) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `codigo_antigo` varchar(12) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `individual` tinyint(1) NOT NULL DEFAULT '1',
  `quantidade_usos` int unsigned NOT NULL DEFAULT '1',
  `tamanho` decimal(10,4) unsigned NOT NULL DEFAULT '1.0000',
  `estoque_minimo` int unsigned NOT NULL DEFAULT '0',
  `finalizado` tinyint(1) NOT NULL DEFAULT '0',
  `data_finalizacao` date DEFAULT NULL,
  `transferido` tinyint(1) NOT NULL DEFAULT '0',
  `data_transferencia` date DEFAULT NULL,
  `impresso` tinyint(1) NOT NULL DEFAULT '1',
  `data_impressao` date DEFAULT NULL,
  `observacao` text CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci,
  `usuario_transferencia_id` int unsigned DEFAULT NULL,
  `estoque_entrada_id` int unsigned NOT NULL,
  `estoque_id` int unsigned NOT NULL,
  `estoque_original_id` int unsigned DEFAULT NULL,
  `produto_id` int unsigned NOT NULL,
  `tonalidade_id` int unsigned DEFAULT NULL,
  `carro_modelo_id` int unsigned DEFAULT NULL,
  `os_servico_id` int unsigned DEFAULT NULL,
  `ativo` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `estoque_fracionamento_id` int unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `estoque_entrada_produtos_usuario_transferencia_id_foreign` (`usuario_transferencia_id`),
  KEY `estoque_entrada_produtos_estoque_entrada_id_foreign` (`estoque_entrada_id`),
  KEY `estoque_entrada_produtos_estoque_id_foreign` (`estoque_id`),
  KEY `estoque_entrada_produtos_estoque_original_id_foreign` (`estoque_original_id`),
  KEY `estoque_entrada_produtos_produto_id_foreign` (`produto_id`),
  KEY `estoque_entrada_produtos_tonalidade_id_foreign` (`tonalidade_id`),
  KEY `estoque_entrada_produtos_estoque_fracionamento_id_foreign` (`estoque_fracionamento_id`),
  KEY `estoque_entrada_produtos_os_servico_id_foreign` (`os_servico_id`),
  KEY `estoque_entrada_produtos_carro_modelo_id_foreign` (`carro_modelo_id`),
  CONSTRAINT `estoque_entrada_produtos_carro_modelo_id_foreign` FOREIGN KEY (`carro_modelo_id`) REFERENCES `carro_modelos` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `estoque_entrada_produtos_estoque_entrada_id_foreign` FOREIGN KEY (`estoque_entrada_id`) REFERENCES `estoque_entradas` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `estoque_entrada_produtos_estoque_fracionamento_id_foreign` FOREIGN KEY (`estoque_fracionamento_id`) REFERENCES `estoque_fracionamentos` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `estoque_entrada_produtos_estoque_id_foreign` FOREIGN KEY (`estoque_id`) REFERENCES `estoques` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `estoque_entrada_produtos_estoque_original_id_foreign` FOREIGN KEY (`estoque_original_id`) REFERENCES `estoques` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `estoque_entrada_produtos_os_servico_id_foreign` FOREIGN KEY (`os_servico_id`) REFERENCES `os_servicos` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `estoque_entrada_produtos_produto_id_foreign` FOREIGN KEY (`produto_id`) REFERENCES `produtos` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `estoque_entrada_produtos_tonalidade_id_foreign` FOREIGN KEY (`tonalidade_id`) REFERENCES `tonalidades` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `estoque_entrada_produtos_usuario_transferencia_id_foreign` FOREIGN KEY (`usuario_transferencia_id`) REFERENCES `usuarios` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=174953 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;