--
-- Table structure for table `estoque_entradas`
--
TABLE `estoque_entradas` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `nota` varchar(30) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `recuperacao` tinyint(1) NOT NULL DEFAULT '0',
  `data_emissao` datetime NOT NULL,
  `total_ipi` decimal(4,2) DEFAULT NULL,
  `total_icms_st` decimal(4,2) DEFAULT NULL,
  `total_produtos` decimal(8,2) DEFAULT NULL,
  `total_tributos` decimal(8,2) DEFAULT NULL,
  `total_nota` decimal(8,2) DEFAULT NULL,
  `possui_frete` tinyint(1) NOT NULL DEFAULT '1',
  `frete` decimal(8,2) DEFAULT NULL,
  `data_vencimento` datetime DEFAULT NULL,
  `seguro` decimal(8,2) DEFAULT NULL,
  `desconto` decimal(4,2) DEFAULT NULL,
  `despesa_acessoria` decimal(8,2) DEFAULT NULL,
  `cancelada` tinyint(1) NOT NULL DEFAULT '0',
  `data_cancelamento` datetime DEFAULT NULL,
  `solicitado_cancelamento` tinyint(1) NOT NULL DEFAULT '0',
  `estoque_id` int unsigned NOT NULL,
  `fornecedor_id` int unsigned DEFAULT NULL,
  `transportadora_id` int unsigned DEFAULT NULL,
  `ordem_compra_id` bigint unsigned DEFAULT NULL,
  `ativo` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `estoque_entradas_estoque_id_foreign` (`estoque_id`),
  KEY `estoque_entradas_fornecedor_id_foreign` (`fornecedor_id`),
  KEY `estoque_entradas_transportadora_id_foreign` (`transportadora_id`),
  KEY `estoque_entradas_ordem_compra_id_foreign` (`ordem_compra_id`),
  CONSTRAINT `estoque_entradas_estoque_id_foreign` FOREIGN KEY (`estoque_id`) REFERENCES `estoques` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `estoque_entradas_fornecedor_id_foreign` FOREIGN KEY (`fornecedor_id`) REFERENCES `fornecedores` (`id`) ON DELETE CASCADE,
  CONSTRAINT `estoque_entradas_ordem_compra_id_foreign` FOREIGN KEY (`ordem_compra_id`) REFERENCES `ordens_compras` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `estoque_entradas_transportadora_id_foreign` FOREIGN KEY (`transportadora_id`) REFERENCES `transportadoras` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=1790 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;