--
-- Table structure for table `funcionario_cargos`
--
TABLE `funcionario_cargos` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `matricula` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `salario` decimal(8,2) NOT NULL,
  `data_admissao` date NOT NULL,
  `demitido` tinyint(1) NOT NULL DEFAULT '0',
  `data_demissao` date DEFAULT NULL,
  `motivo_demissao` text CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci,
  `fixo` tinyint(1) NOT NULL DEFAULT '0',
  `reemprego` tinyint(1) NOT NULL DEFAULT '0',
  `periodo_experiencia` tinyint(1) NOT NULL DEFAULT '0',
  `inicio_experiencia` date DEFAULT NULL,
  `fim_experiencia` date DEFAULT NULL,
  `funcionario_id` int unsigned NOT NULL,
  `cargo_id` int unsigned NOT NULL,
  `empresa_id` int unsigned DEFAULT NULL,
  `produtivo_tipo_id` int unsigned DEFAULT NULL,
  `funcionario_local_id` bigint unsigned DEFAULT NULL,
  `concessionaria_local_id` int unsigned DEFAULT NULL,
  `ativo` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `funcionario_cargos_funcionario_id_foreign` (`funcionario_id`),
  KEY `funcionario_cargos_cargo_id_foreign` (`cargo_id`),
  KEY `funcionario_cargos_produtivo_tipo_id_foreign` (`produtivo_tipo_id`),
  KEY `funcionario_cargos_empresa_id_foreign` (`empresa_id`),
  KEY `funcionario_cargos_funcionario_local_id_foreign` (`funcionario_local_id`),
  KEY `funcionario_cargos_concessionaria_local_id_foreign` (`concessionaria_local_id`),
  CONSTRAINT `funcionario_cargos_cargo_id_foreign` FOREIGN KEY (`cargo_id`) REFERENCES `cargos` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `funcionario_cargos_concessionaria_local_id_foreign` FOREIGN KEY (`concessionaria_local_id`) REFERENCES `concessionarias` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `funcionario_cargos_empresa_id_foreign` FOREIGN KEY (`empresa_id`) REFERENCES `empresas` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `funcionario_cargos_funcionario_id_foreign` FOREIGN KEY (`funcionario_id`) REFERENCES `funcionarios` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `funcionario_cargos_funcionario_local_id_foreign` FOREIGN KEY (`funcionario_local_id`) REFERENCES `funcionario_locais` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `funcionario_cargos_produtivo_tipo_id_foreign` FOREIGN KEY (`produtivo_tipo_id`) REFERENCES `produtivo_tipos` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=715 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;