--
-- Table structure for table `notas_fiscais`
--
TABLE `notas_fiscais` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `valor_bruto` decimal(8,2) NOT NULL,
  `valor_liquido` decimal(8,2) NOT NULL,
  `retencao_iss` tinyint(1) NOT NULL DEFAULT '0',
  `data_emissao` datetime DEFAULT NULL,
  `tipo_nota` varchar(2) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `serie` int NOT NULL DEFAULT '1',
  `bancotoyota` tinyint(1) NOT NULL DEFAULT '0',
  `numero_nota` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `chave_nota` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `numero_registro` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `status_nota` int unsigned NOT NULL,
  `danfe_emitida` int NOT NULL DEFAULT '0',
  `email_enviado` tinyint(1) NOT NULL DEFAULT '0',
  `url_danfe` varchar(150) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `resposta_erro` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `cancelada` tinyint(1) NOT NULL DEFAULT '0',
  `data_cancelamento` datetime DEFAULT NULL,
  `solicitado_cancelamento` tinyint(1) NOT NULL DEFAULT '0',
  `motivo_cancelamento` text CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci,
  `devolvida` tinyint(1) NOT NULL DEFAULT '0',
  `data_devolucao` datetime DEFAULT NULL,
  `solicitado_devolucao` tinyint(1) NOT NULL DEFAULT '0',
  `cancelamento_extemporaneo` tinyint(1) NOT NULL DEFAULT '0',
  `data_cancelamento_extemporaneo` datetime DEFAULT NULL,
  `solicitado_cancelamento_extemporaneo` tinyint(1) NOT NULL DEFAULT '0',
  `observacao_devolucao` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `devolucao_pelo_cliente` tinyint(1) NOT NULL DEFAULT '0',
  `chave_nfe_referencia` varchar(44) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `chave_cte_referencia` varchar(44) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `observacao` text CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci,
  `info_adicional` text CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci,
  `natureza_operacao` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `boleto_emitido` tinyint(1) NOT NULL DEFAULT '0',
  `url_boleto` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `data_emissao_boleto` datetime DEFAULT NULL,
  `data_vencimento_boleto` datetime DEFAULT NULL,
  `boleto_registrado` tinyint(1) NOT NULL DEFAULT '0',
  `data_registro_boleto` datetime DEFAULT NULL,
  `lancado_moneycare` tinyint(1) NOT NULL DEFAULT '0',
  `data_lancamento_moneycare` datetime DEFAULT NULL,
  `os_id` int unsigned DEFAULT NULL,
  `cortesia_id` int unsigned DEFAULT NULL,
  `fornecedor_id` int unsigned DEFAULT NULL,
  `parent_id` int unsigned DEFAULT NULL,
  `boleto_remessa_id` bigint unsigned DEFAULT NULL,
  `empresa_id` int unsigned NOT NULL,
  `ativo` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `notas_fiscais_os_id_foreign` (`os_id`),
  KEY `notas_fiscais_cortesia_id_foreign` (`cortesia_id`),
  KEY `notas_fiscais_empresa_id_foreign` (`empresa_id`),
  KEY `notas_fiscais_fornecedor_id_foreign` (`fornecedor_id`),
  KEY `notas_fiscais_boleto_remessa_id_foreign` (`boleto_remessa_id`),
  KEY `notas_fiscais_tipo_nota_index` (`tipo_nota`),
  KEY `notas_fiscais_numero_nota_index` (`numero_nota`),
  KEY `notas_fiscais_cancelada_index` (`cancelada`),
  KEY `notas_fiscais_status_nota_index` (`status_nota`),
  KEY `notas_fiscais_resposta_erro_index` (`resposta_erro`(768)),
  KEY `notas_fiscais_chave_nota_index` (`chave_nota`),
  KEY `notas_fiscais_parent_id_foreign` (`parent_id`),
  CONSTRAINT `notas_fiscais_boleto_remessa_id_foreign` FOREIGN KEY (`boleto_remessa_id`) REFERENCES `boleto_remessas` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `notas_fiscais_cortesia_id_foreign` FOREIGN KEY (`cortesia_id`) REFERENCES `cortesias` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `notas_fiscais_empresa_id_foreign` FOREIGN KEY (`empresa_id`) REFERENCES `empresas` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `notas_fiscais_fornecedor_id_foreign` FOREIGN KEY (`fornecedor_id`) REFERENCES `fornecedores` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `notas_fiscais_os_id_foreign` FOREIGN KEY (`os_id`) REFERENCES `os` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `notas_fiscais_parent_id_foreign` FOREIGN KEY (`parent_id`) REFERENCES `notas_fiscais` (`id`),
  CONSTRAINT `notas_fiscais_status_nota_foreign` FOREIGN KEY (`status_nota`) REFERENCES `nota_fiscal_statuses` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=144083 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;