--
-- Table structure for table `os`
--
TABLE `os` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `os_concessionaria` int unsigned NOT NULL,
  `tipo_atendimento` enum('PRESENCIAL','TELEFONE','WHATSAPP') CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `valor_bruto` decimal(8,2) unsigned NOT NULL DEFAULT '0.00',
  `valor_liquido` decimal(8,2) unsigned NOT NULL DEFAULT '0.00',
  `retencao_iss` tinyint(1) NOT NULL DEFAULT '0',
  `paga` tinyint(1) NOT NULL DEFAULT '0',
  `data_pagamento` datetime DEFAULT NULL,
  `observacao_pagamento` text CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci,
  `usuario_pagamento_id` int unsigned DEFAULT NULL,
  `fechada` tinyint(1) NOT NULL DEFAULT '0',
  `data_fechamento` datetime DEFAULT NULL,
  `finalizada` tinyint(1) NOT NULL DEFAULT '0',
  `data_finalizacao` datetime DEFAULT NULL,
  `cancelada` tinyint(1) NOT NULL DEFAULT '0',
  `data_cancelamento` datetime DEFAULT NULL,
  `solicitado_cancelamento` tinyint(1) NOT NULL DEFAULT '0',
  `motivo_cancelamento` text CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci,
  `cancelamento_recusado` tinyint(1) DEFAULT NULL,
  `data_recusa_cancelamento` datetime DEFAULT NULL,
  `cancelamento_motivo_id` int unsigned DEFAULT NULL,
  `contato_cliente_cancelamento` tinyint(1) DEFAULT NULL,
  `descricao_contato_cancelamento` text CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci,
  `os_retorno` tinyint(1) NOT NULL DEFAULT '0',
  `atendimento_telefonico` tinyint(1) NOT NULL DEFAULT '0',
  `nota_solicitada` tinyint(1) NOT NULL DEFAULT '0',
  `nota_solicitada_motivo` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `data_solicitacao_nfe` datetime DEFAULT NULL,
  `nota_aprovada` tinyint(1) NOT NULL DEFAULT '0',
  `data_aprovacao_nfe` datetime DEFAULT NULL,
  `usuario_aprovacao_nfe_id` int unsigned DEFAULT NULL,
  `cep` varchar(8) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `logradouro` varchar(80) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `bairro` varchar(80) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `localidade` varchar(80) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `uf` char(2) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `numero` int DEFAULT NULL,
  `complemento` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `data_entrega` datetime DEFAULT NULL,
  `data_edicao_entrega` datetime DEFAULT NULL,
  `entrega_confirmada` tinyint(1) NOT NULL DEFAULT '0',
  `data_confirmacao_entrega` datetime DEFAULT NULL,
  `execucao_mesmo_dia` tinyint(1) NOT NULL DEFAULT '0',
  `email_garantia_enviado` tinyint(1) NOT NULL DEFAULT '0',
  `data_envio_garantia` datetime DEFAULT NULL,
  `observacao_os` text CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci,
  `observacao_producao` text CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci,
  `observacao_nf` text CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci,
  `justificada_concessionaria` tinyint(1) NOT NULL DEFAULT '0',
  `desconto_Avista` tinyint(1) NOT NULL DEFAULT '0',
  `confirmar_retem_iss` tinyint(1) NOT NULL DEFAULT '0',
  `cortesia_migrada` tinyint(1) NOT NULL DEFAULT '0',
  `data_migracao_cortesia` date DEFAULT NULL,
  `nome_responsavel_pj` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `cpf_responsavel_pj` varchar(14) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `nivel_indicador1` int unsigned DEFAULT NULL,
  `nivel_indicador2` int unsigned DEFAULT NULL,
  `indicador1_id` int unsigned DEFAULT NULL,
  `indicador2_id` int unsigned DEFAULT NULL,
  `departamento_id` int unsigned NOT NULL,
  `vendedor_id` int unsigned NOT NULL,
  `concessionaria_id` int unsigned NOT NULL,
  `cliente_carro_id` int unsigned NOT NULL,
  `cliente_id` int unsigned NOT NULL,
  `os_tipo_id` int unsigned NOT NULL,
  `proposta_id` int unsigned DEFAULT NULL,
  `pre_proposta_id` bigint unsigned DEFAULT NULL,
  `os_retorno_id` int unsigned DEFAULT NULL,
  `os_migracao_cortesia_id` int DEFAULT NULL,
  `usuario_recusa_cancelamento_id` int unsigned DEFAULT NULL,
  `funcionario_confirmacao_entrega_id` int unsigned DEFAULT NULL,
  `ativo` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `id_antigo` int DEFAULT NULL,
  `usuario_atendimento_cancelamento_id` int unsigned DEFAULT NULL,
  `justificativa_supervisao` int DEFAULT NULL,
  `justificativa_supervisao_usuario_id` int DEFAULT NULL,
  `justificativa_supervisao_texto` text CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci,
  PRIMARY KEY (`id`),
  KEY `os_indicador1_id_foreign` (`indicador1_id`),
  KEY `os_indicador2_id_foreign` (`indicador2_id`),
  KEY `os_departamento_id_foreign` (`departamento_id`),
  KEY `os_concessionaria_id_foreign` (`concessionaria_id`),
  KEY `os_cliente_carro_id_foreign` (`cliente_carro_id`),
  KEY `os_cliente_id_foreign` (`cliente_id`),
  KEY `os_os_tipo_id_foreign` (`os_tipo_id`),
  KEY `os_os_retorno_id_foreign` (`os_retorno_id`),
  KEY `os_cancelamento_motivo_id_foreign` (`cancelamento_motivo_id`),
  KEY `os_vendedor_id_foreign` (`vendedor_id`),
  KEY `os_usuario_aprovacao_nfe_id_foreign` (`usuario_aprovacao_nfe_id`),
  KEY `os_usuario_recusa_cancelamento_id_foreign` (`usuario_recusa_cancelamento_id`),
  KEY `os_usuario_atendimento_cancelamento_id_foreign` (`usuario_atendimento_cancelamento_id`),
  KEY `os_usuario_pagamento_id_foreign` (`usuario_pagamento_id`),
  KEY `os_migracao_cortesia_id_index` (`os_migracao_cortesia_id`),
  KEY `os_proposta_id_foreign` (`proposta_id`),
  KEY `os_pre_proposta_id_foreign` (`pre_proposta_id`),
  KEY `os_paga` (`paga`),
  KEY `os_cancelada` (`cancelada`),
  KEY `os_data_pagamento` (`data_pagamento`),
  KEY `os_data_cancelamento` (`data_cancelamento`),
  KEY `os_created_at` (`created_at`),
  KEY `os_deleted_at` (`deleted_at`),
  KEY `os.data_entrega` (`data_entrega`),
  KEY `os_fechada` (`fechada`),
  KEY `produtividade` (`deleted_at`,`cancelada`,`concessionaria_id`),
  KEY `os_funcionario_confirmacao_entrega_id_foreign` (`funcionario_confirmacao_entrega_id`),
  CONSTRAINT `os_cancelamento_motivo_id_foreign` FOREIGN KEY (`cancelamento_motivo_id`) REFERENCES `cancelamento_motivos` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `os_cliente_carro_id_foreign` FOREIGN KEY (`cliente_carro_id`) REFERENCES `cliente_carros` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `os_cliente_id_foreign` FOREIGN KEY (`cliente_id`) REFERENCES `clientes` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `os_concessionaria_id_foreign` FOREIGN KEY (`concessionaria_id`) REFERENCES `concessionarias` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `os_departamento_id_foreign` FOREIGN KEY (`departamento_id`) REFERENCES `departamentos` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `os_funcionario_confirmacao_entrega_id_foreign` FOREIGN KEY (`funcionario_confirmacao_entrega_id`) REFERENCES `funcionarios` (`id`),
  CONSTRAINT `os_indicador1_id_foreign` FOREIGN KEY (`indicador1_id`) REFERENCES `indicadores` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `os_indicador2_id_foreign` FOREIGN KEY (`indicador2_id`) REFERENCES `indicadores` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `os_os_retorno_id_foreign` FOREIGN KEY (`os_retorno_id`) REFERENCES `os` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `os_os_tipo_id_foreign` FOREIGN KEY (`os_tipo_id`) REFERENCES `os_tipos` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `os_pre_proposta_id_foreign` FOREIGN KEY (`pre_proposta_id`) REFERENCES `pre_propostas` (`id`),
  CONSTRAINT `os_proposta_id_foreign` FOREIGN KEY (`proposta_id`) REFERENCES `propostas` (`id`),
  CONSTRAINT `os_usuario_aprovacao_nfe_id_foreign` FOREIGN KEY (`usuario_aprovacao_nfe_id`) REFERENCES `funcionarios` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `os_usuario_atendimento_cancelamento_id_foreign` FOREIGN KEY (`usuario_atendimento_cancelamento_id`) REFERENCES `funcionarios` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `os_usuario_pagamento_id_foreign` FOREIGN KEY (`usuario_pagamento_id`) REFERENCES `funcionarios` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `os_usuario_recusa_cancelamento_id_foreign` FOREIGN KEY (`usuario_recusa_cancelamento_id`) REFERENCES `funcionarios` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `os_vendedor_id_foreign` FOREIGN KEY (`vendedor_id`) REFERENCES `funcionarios` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=148149 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;