--
-- Table structure for table `os_retornos`
--
TABLE `os_retornos` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `descricao` text CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci,
  `data_solicitacao` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `data_aprovacao` datetime DEFAULT NULL,
  `data_recusa` datetime DEFAULT NULL,
  `os_origem_id` int unsigned NOT NULL,
  `os_destino_id` int unsigned DEFAULT NULL,
  `retorno_motivo_id` int unsigned NOT NULL,
  `retorno_classificacao_id` int unsigned DEFAULT NULL,
  `usuario_solicitacao_id` int unsigned NOT NULL,
  `usuario_aprovacao_id` int unsigned DEFAULT NULL,
  `usuario_recusa_id` int unsigned DEFAULT NULL,
  `aprovado` tinyint(1) NOT NULL DEFAULT '0',
  `recusado` tinyint(1) NOT NULL DEFAULT '0',
  `ativo` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `orooi` (`os_origem_id`),
  KEY `orodi` (`os_destino_id`),
  KEY `orrmi` (`retorno_motivo_id`),
  KEY `orusi` (`usuario_solicitacao_id`),
  KEY `oruai` (`usuario_aprovacao_id`),
  KEY `oruri` (`usuario_recusa_id`),
  KEY `os_retornos_retorno_classificacao_id_foreign` (`retorno_classificacao_id`),
  CONSTRAINT `orodi` FOREIGN KEY (`os_destino_id`) REFERENCES `os` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `orooi` FOREIGN KEY (`os_origem_id`) REFERENCES `os` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `orrmi` FOREIGN KEY (`retorno_motivo_id`) REFERENCES `retorno_motivos` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `oruai` FOREIGN KEY (`usuario_aprovacao_id`) REFERENCES `funcionarios` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `oruri` FOREIGN KEY (`usuario_recusa_id`) REFERENCES `funcionarios` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `orusi` FOREIGN KEY (`usuario_solicitacao_id`) REFERENCES `funcionarios` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `os_retornos_retorno_classificacao_id_foreign` FOREIGN KEY (`retorno_classificacao_id`) REFERENCES `retorno_classificacoes` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=6101 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;