--
-- Table structure for table `plotter_saida_cortes`
--
TABLE `plotter_saida_cortes` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `duas_portas` tinyint(1) NOT NULL DEFAULT '0',
  `credito_minimo` int unsigned NOT NULL DEFAULT '0',
  `credito_maximo` int unsigned NOT NULL DEFAULT '0',
  `ano_modelo` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cancelado` tinyint(1) NOT NULL DEFAULT '0',
  `data_cancelamento` datetime DEFAULT NULL,
  `motivo_cancelamento` enum('incoerencia','em_falta','requisicao_cancelada','estoque_programado_cancelado','devolucao') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `plotter_corte_tipo_id` int unsigned NOT NULL,
  `plotter_peca_id` int unsigned DEFAULT NULL,
  `carro_modelo_id` int unsigned DEFAULT NULL,
  `produto_id` int unsigned NOT NULL,
  `tonalidade_id` int unsigned DEFAULT NULL,
  `produto_traseiro_id` int unsigned DEFAULT NULL,
  `tonalidade_traseiro_id` int unsigned DEFAULT NULL,
  `produto_dianteiro_id` int unsigned DEFAULT NULL,
  `tonalidade_dianteiro_id` int unsigned DEFAULT NULL,
  `plotter_saida_id` bigint unsigned NOT NULL,
  `plotter_corte_id` int unsigned DEFAULT NULL,
  `os_servico_id` int unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `pscpcti` (`plotter_corte_tipo_id`),
  KEY `psccmi` (`carro_modelo_id`),
  KEY `pscpi` (`produto_id`),
  KEY `pscti` (`tonalidade_id`),
  KEY `pscpti` (`produto_traseiro_id`),
  KEY `psctti` (`tonalidade_traseiro_id`),
  KEY `pscpdi` (`produto_dianteiro_id`),
  KEY `psctdi` (`tonalidade_dianteiro_id`),
  KEY `pscpsi` (`plotter_saida_id`),
  KEY `pscpci` (`plotter_corte_id`),
  KEY `pscosi` (`os_servico_id`),
  KEY `plotter_saida_cortes_plotter_peca_id_foreign` (`plotter_peca_id`),
  CONSTRAINT `plotter_saida_cortes_plotter_peca_id_foreign` FOREIGN KEY (`plotter_peca_id`) REFERENCES `plotter_pecas` (`id`),
  CONSTRAINT `psccmi` FOREIGN KEY (`carro_modelo_id`) REFERENCES `carro_modelos` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `pscosi` FOREIGN KEY (`os_servico_id`) REFERENCES `os_servicos` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `pscpci` FOREIGN KEY (`plotter_corte_id`) REFERENCES `plotter_cortes` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `pscpcti` FOREIGN KEY (`plotter_corte_tipo_id`) REFERENCES `plotter_corte_tipos` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `pscpdi` FOREIGN KEY (`produto_dianteiro_id`) REFERENCES `produtos` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `pscpi` FOREIGN KEY (`produto_id`) REFERENCES `produtos` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `pscpsi` FOREIGN KEY (`plotter_saida_id`) REFERENCES `plotter_saidas` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `pscpti` FOREIGN KEY (`produto_traseiro_id`) REFERENCES `produtos` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `psctdi` FOREIGN KEY (`tonalidade_dianteiro_id`) REFERENCES `tonalidades` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `pscti` FOREIGN KEY (`tonalidade_id`) REFERENCES `tonalidades` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `psctti` FOREIGN KEY (`tonalidade_traseiro_id`) REFERENCES `tonalidades` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=221395 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;