--
-- Table structure for table `plotter_estoques_programados`
--
TABLE `plotter_estoques_programados` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `minimo` int unsigned NOT NULL,
  `maximo` int unsigned NOT NULL,
  `credito_minimo` int unsigned NOT NULL DEFAULT '0',
  `credito_maximo` int unsigned NOT NULL DEFAULT '0',
  `tipo_estoque` enum('concessionaria','plotter') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `produto_id` int unsigned NOT NULL,
  `tonalidade_id` int unsigned DEFAULT NULL,
  `plotter_corte_tipo_id` int unsigned NOT NULL,
  `plotter_peca_id` int unsigned DEFAULT NULL,
  `concessionaria_id` int unsigned DEFAULT NULL,
  `estoque_id` int unsigned DEFAULT NULL,
  `carro_modelo_id` int unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `peppi` (`produto_id`),
  KEY `pepti` (`tonalidade_id`),
  KEY `peppcti` (`plotter_corte_tipo_id`),
  KEY `pepci` (`concessionaria_id`),
  KEY `pepcmi` (`carro_modelo_id`),
  KEY `pepei` (`estoque_id`),
  KEY `plotter_estoques_programados_plotter_peca_id_foreign` (`plotter_peca_id`),
  CONSTRAINT `pepci` FOREIGN KEY (`concessionaria_id`) REFERENCES `concessionarias` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `pepcmi` FOREIGN KEY (`carro_modelo_id`) REFERENCES `carro_modelos` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `pepei` FOREIGN KEY (`estoque_id`) REFERENCES `estoques` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `peppcti` FOREIGN KEY (`plotter_corte_tipo_id`) REFERENCES `plotter_corte_tipos` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `peppi` FOREIGN KEY (`produto_id`) REFERENCES `produtos` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `pepti` FOREIGN KEY (`tonalidade_id`) REFERENCES `tonalidades` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `plotter_estoques_programados_plotter_peca_id_foreign` FOREIGN KEY (`plotter_peca_id`) REFERENCES `plotter_pecas` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=796 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;