--
-- Table structure for table `propostas`
--
TABLE `propostas` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `proposta_concessionaria` int unsigned NOT NULL,
  `tipo_atendimento` enum('PRESENCIAL','TELEFONE','WHATSAPP') CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `nome` varchar(120) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `sexo` enum('MASCULINO','FEMININO','NEUTRO','NÃO INFORMADO') CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `telefone1` varchar(15) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `telefone2` varchar(15) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `email` varchar(80) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `atendimento_telefonico` tinyint(1) NOT NULL DEFAULT '0',
  `justificativa` text CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci,
  `cancelamento_motivo_id` int unsigned DEFAULT NULL,
  `vendedor_id` int unsigned NOT NULL,
  `concessionaria_id` int unsigned NOT NULL,
  `departamento_id` int unsigned NOT NULL,
  `cliente_id` int unsigned DEFAULT NULL,
  `cliente_carro_id` int unsigned DEFAULT NULL,
  `proposta_status_id` int unsigned NOT NULL,
  `carro_modelo_id` int unsigned DEFAULT NULL,
  `carro_submodelo_id` int unsigned DEFAULT NULL,
  `carro_cor_id` int unsigned DEFAULT NULL,
  `pre_proposta_id` bigint unsigned DEFAULT NULL,
  `ativo` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `propostas_concessionaria_id_foreign` (`concessionaria_id`),
  KEY `propostas_departamento_id_foreign` (`departamento_id`),
  KEY `propostas_cliente_id_foreign` (`cliente_id`),
  KEY `propostas_cliente_carro_id_foreign` (`cliente_carro_id`),
  KEY `propostas_proposta_status_id_foreign` (`proposta_status_id`),
  KEY `propostas_cancelamento_motivo_id_foreign` (`cancelamento_motivo_id`),
  KEY `propostas_vendedor_id_foreign` (`vendedor_id`),
  KEY `propostas_carro_modelo_id_foreign` (`carro_modelo_id`),
  KEY `propostas_carro_submodelo_id_foreign` (`carro_submodelo_id`),
  KEY `propostas_carro_cor_id_foreign` (`carro_cor_id`),
  KEY `propostas_pre_proposta_id_foreign` (`pre_proposta_id`),
  CONSTRAINT `propostas_cancelamento_motivo_id_foreign` FOREIGN KEY (`cancelamento_motivo_id`) REFERENCES `cancelamento_motivos` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `propostas_carro_cor_id_foreign` FOREIGN KEY (`carro_cor_id`) REFERENCES `carro_cores` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `propostas_carro_modelo_id_foreign` FOREIGN KEY (`carro_modelo_id`) REFERENCES `carro_modelos` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `propostas_carro_submodelo_id_foreign` FOREIGN KEY (`carro_submodelo_id`) REFERENCES `carro_submodelos` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `propostas_cliente_carro_id_foreign` FOREIGN KEY (`cliente_carro_id`) REFERENCES `cliente_carros` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `propostas_cliente_id_foreign` FOREIGN KEY (`cliente_id`) REFERENCES `clientes` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `propostas_concessionaria_id_foreign` FOREIGN KEY (`concessionaria_id`) REFERENCES `concessionarias` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `propostas_departamento_id_foreign` FOREIGN KEY (`departamento_id`) REFERENCES `departamentos` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `propostas_pre_proposta_id_foreign` FOREIGN KEY (`pre_proposta_id`) REFERENCES `pre_propostas` (`id`),
  CONSTRAINT `propostas_proposta_status_id_foreign` FOREIGN KEY (`proposta_status_id`) REFERENCES `proposta_status` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `propostas_vendedor_id_foreign` FOREIGN KEY (`vendedor_id`) REFERENCES `funcionarios` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=98325 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;