--
-- Table structure for table `servicos`
--
TABLE `servicos` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `nome` varchar(200) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `custo_fixo` decimal(8,2) unsigned NOT NULL DEFAULT '0.00',
  `codigo_nf` varchar(30) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `fecha_kit` tinyint(1) NOT NULL DEFAULT '0',
  `fecha_peca_avulsa` tinyint(1) NOT NULL DEFAULT '0',
  `fecha_peca` tinyint(1) NOT NULL DEFAULT '0',
  `fecha_produto` tinyint(1) NOT NULL DEFAULT '0',
  `fecha_produtivo` tinyint(1) NOT NULL DEFAULT '1',
  `diferencia_departamento_preco` tinyint(1) NOT NULL DEFAULT '0',
  `diferencia_porte` tinyint(1) NOT NULL DEFAULT '0',
  `diferencia_departamento` tinyint(1) NOT NULL DEFAULT '0',
  `diferencia_porte_comissao` tinyint(1) NOT NULL DEFAULT '0',
  `diferencia_tempo_departamento` tinyint(1) NOT NULL DEFAULT '1',
  `diferencia_tempo_cor` tinyint(1) NOT NULL DEFAULT '0',
  `credito_necessario` int unsigned NOT NULL DEFAULT '0',
  `valor_desconto_cortesia` decimal(8,2) unsigned NOT NULL DEFAULT '0.00',
  `aceita_desconto_cortesia` tinyint(1) NOT NULL DEFAULT '0',
  `segunda_aplicacao` tinyint(1) NOT NULL DEFAULT '0',
  `grupo_servico_id` int unsigned NOT NULL,
  `subgrupo_servico_id` int unsigned NOT NULL,
  `servico_categoria_id` bigint unsigned DEFAULT NULL,
  `tags` varchar(30) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `ativo` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `servicos_grupo_servico_id_foreign` (`grupo_servico_id`),
  KEY `servicos_subgrupo_servico_id_foreign` (`subgrupo_servico_id`),
  KEY `servicos_fecha_produtivo` (`fecha_produtivo`),
  KEY `servicos_deleted_at` (`deleted_at`),
  KEY `servicos_ativos` (`ativo`,`diferencia_departamento_preco`,`diferencia_departamento`,`diferencia_porte`,`deleted_at`),
  KEY `servicos_servico_categoria_id_foreign` (`servico_categoria_id`),
  CONSTRAINT `servicos_grupo_servico_id_foreign` FOREIGN KEY (`grupo_servico_id`) REFERENCES `grupos_servicos` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `servicos_servico_categoria_id_foreign` FOREIGN KEY (`servico_categoria_id`) REFERENCES `servico_categorias` (`id`),
  CONSTRAINT `servicos_subgrupo_servico_id_foreign` FOREIGN KEY (`subgrupo_servico_id`) REFERENCES `subgrupos_servicos` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=129 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;